spring:
  main:
    banner-mode: off
  #liquibase not in use
  datasource:
    url: jdbc:postgresql://localhost:5555/blacklist
    password: zveron_password
    username: zveron_user
  liquibase:
    enabled: false
  #[--------------------------]
  application:
    name: zv-eureka-server
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration, org.springframework.boot.actuate.autoconfigure.audit.AuditEventsEndpointAutoConfiguration, org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.web.embedded.EmbeddedWebServerFactoryCustomizerAutoConfiguration, org.springframework.cloud.client.discovery.composite.reactive.ReactiveCompositeDiscoveryClientAutoConfiguration, org.springframework.boot.autoconfigure.web.reactive.ReactiveWebServerFactoryAutoConfiguration, org.springframework.boot.autoconfigure.web.reactive.function.client.WebClientAutoConfiguration,

eureka:
  instance:
    hostname: localhost # should be put into vault
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    appname: zv-eureka-instance
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    refresh:
      enable: true
    eureka-server-total-connections: 20
  server:
    enable-self-preservation: true
    registry-sync-retries: 3
    registry-sync-retry-wait-ms: 300
    max-threads-for-peer-replication: 2
    remote-region-fetch-thread-pool-size: 5

server:
  port: 8761
  tomcat:
    threads:
      max: 50
      min-spare: 5