-- changeset sofia.terekhova:1671303542606-1
CREATE SEQUENCE IF NOT EXISTS public.address_id_seq START WITH 1 INCREMENT BY 1;

-- changeset sofia.terekhova:1671303542606-2
CREATE TABLE public.address
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    district  VARCHAR(255),
    house     VARCHAR(255),
    latitude  FLOAT8                                  NOT NULL,
    longitude FLOAT8                                  NOT NULL,
    region    VARCHAR(255),
    street    VARCHAR(255),
    town      VARCHAR(255),
    CONSTRAINT "addressPK" PRIMARY KEY (id)
);

-- changeset sofia.terekhova:1671303542606-3
ALTER TABLE public.address
    ADD CONSTRAINT "UK8unp71l1qqu2fqir4qhhjp5hb" UNIQUE (longitude, latitude);