-- changeset Schuyweiz:init_subway_table
CREATE TABLE IF NOT EXISTS public.subway_station
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100),
    color_hex VARCHAR(8),
    city      VARCHAR(50),

    CONSTRAINT "subway_station_pk" PRIMARY KEY (id)
);