package ru.zveron.model.search.table

import org.jooq.Record
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
object LOT_PARAMETER : TableImpl<Record>(DSL.name("lot_parameter"), null) {

    /**
     * The column `public.lot_parameter.id_lot`.
     */
    val ID_LOT = createField(DSL.name("lot_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column `public.lot_parameter.id_parameter`.
     */
    val ID_PARAMETER = createField(DSL.name("parameter_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column `public.lot_parameter.value`.
     */
    val VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255), this, "")
}
