grpc:
  server:
    port: 0
  client:
    blacklist-service:
      address: 'discovery:///blacklist-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    profile-service:
      address: 'discovery:///profile-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    lot-service:
      address: 'discovery:///lot-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


server:
  port: 0



spring:
  main:
    banner-mode: off
  application:
    name: chat-service
  data:
    cassandra:
      keyspace-name: zveron_chat
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    metadata-map:
      ChatServiceExternal: 'chat_external.proto'



platform:
  grpc:
    apigateway:
      metadata: true
    client:
      logging-enabled: true
    server:
      logging-enabled: true