grpc:
  server:
    port: 0
  client:
    blacklist-client:
      address: 'discovery:///blacklist-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    profile-client:
      address: 'discovery:///profile-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    lot-client:
      address: 'discovery:///lot-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


server:
  port: 0

service:
  persistence:
    chat:
      pagination-size: 100
    message:
      pagination-size: 100
    connection:
      buffer-size: 50

spring:
  main:
    banner-mode: off
  application:
    name: chat-service
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: chat-consumer



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    metadata-map:
      ChatServiceExternal: 'chat_external.proto'
      PingServiceExternal: 'ping_external.proto'



platform:
  grpc:
    apigateway:
      metadata: true
    client:
      logging-enabled: true
    server:
      logging-enabled: true