-- liquibase formatted sql

-- changeset dakochik:1675708635459-1
CREATE SEQUENCE IF NOT EXISTS public.communication_link_id_seq START WITH 1 INCREMENT BY 1;

-- changeset dakochik:1675708635459-2
CREATE TABLE public.communication_link
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    communication_link_id VARCHAR(20)                             NOT NULL,
    data                  JSONB                                   NOT NULL,
    profile_id            BIGINT                                  NOT NULL,
    CONSTRAINT "communication_linkPK" PRIMARY KEY (id)
);

-- changeset dakochik:1675708635459-3
ALTER TABLE public.communication_link
    ADD CONSTRAINT "communication_link_refer_profile_constraint" FOREIGN KEY (profile_id)
        REFERENCES public.profile (id);

-- changeset dakochik:1675708635459-4
ALTER TABLE public.contact DROP CONSTRAINT contact_refer_profile_constraint;

-- changeset dakochik:1675708635459-5
DROP TABLE public.contact;

-- changeset Dmitry.Kochik:1675708635459-6
CREATE INDEX communication_link_context_id_index ON public.communication_link (communication_link_id);

-- changeset Dmitry.Kochik:1675708635459-7
CREATE INDEX communication_link_profile_id_index ON public.communication_link (profile_id);
