-- liquibase formatted sql

-- changeset WolfAlm:1673359760919-1
CREATE SEQUENCE IF NOT EXISTS public.lot_id_seq START WITH 1 INCREMENT BY 1;

-- changeset WolfAlm:1673359760919-2
CREATE SEQUENCE IF NOT EXISTS public.lot_photo_id_seq START WITH 1 INCREMENT BY 1;

-- changeset WolfAlm:1673359760919-3
CREATE TABLE public.lot
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_id            BIGINT,
    category_id           INTEGER,
    date_creation         TIMESTAMP WITHOUT TIME ZONE,
    description           VARCHAR(2000),
    gender                INTEGER,
    lot_form_id           INTEGER,
    price                 INTEGER                                 NOT NULL,
    seller_id             BIGINT,
    status                VARCHAR(20),
    title                 VARCHAR(150),
    ways_of_communicating JSONB,
    CONSTRAINT "lotPK" PRIMARY KEY (id)
);

-- changeset WolfAlm:1673359760919-4
CREATE TABLE public.lot_photo
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_id    BIGINT                                  NOT NULL,
    order_photo INTEGER,
    lot_id      BIGINT                                  NOT NULL,
    CONSTRAINT "lot_photoPK" PRIMARY KEY (id)
);

-- changeset WolfAlm:1673359760919-5
CREATE TABLE public.lot_statistics
(
    quantity_favorite INTEGER NOT NULL,
    quantity_view     INTEGER NOT NULL,
    lot_id            BIGINT  NOT NULL,
    CONSTRAINT "lot_statisticsPK" PRIMARY KEY (lot_id)
);

-- changeset WolfAlm:1673359760919-6
CREATE TABLE public.possible_customer
(
    lot_id                         BIGINT NOT NULL,
    profile_id                     BIGINT NOT NULL,
    date_of_conversation_beginning TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT "possible_customerPK" PRIMARY KEY (lot_id, profile_id)
);

-- changeset WolfAlm:1673359760919-7
ALTER TABLE public.lot_photo
    ADD CONSTRAINT "FK1pkjrmj021ynruj77ijbntlrt" FOREIGN KEY (lot_id) REFERENCES public.lot (id);

-- changeset WolfAlm:1673359760919-8
ALTER TABLE public.possible_customer
    ADD CONSTRAINT "FKc0rft90dckn2sd24an21fecso" FOREIGN KEY (lot_id) REFERENCES public.lot (id);

-- changeset WolfAlm:1673359760919-9
ALTER TABLE public.lot_statistics
    ADD CONSTRAINT "FKow1siui5g2gvovlntjc83a88d" FOREIGN KEY (lot_id) REFERENCES public.lot (id);

