name: "Label PR"

on:
  - pull_request

jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  Test labeled modules:
    uses: ./.github/workflows/tester.yml